stages:
  - build
  - deploy

build:
  stage: build
  script:
    - cd /server
    - docker-compose build kiosk

deploy:
  stage: deploy
  script:
    - cd /server
    - docker-compose up -d kiosk
  only:
    - main