stages:
  - pull
  - build
  - deploy

before_script:
  - cd $DOCKER_COMPOSE_PATH

pull:
  stage: pull
  script:
    - docker-compose -p kiosk -f docker-compose.kiosk.yml stop kiosk
    - cd $PROJECT_PATH
    - git pull
  only:
    - main
  tags:
    - docker

    

build:
  stage: build
  script:
    - docker-compose -p kiosk -f docker-compose.kiosk.yml build kiosk
  only:
    - main
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - docker-compose -p kiosk -f docker-compose.kiosk.yml up -d
  only:
    - main
  tags:
    - docker
