stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build_image:
  stage: build
  script:
    - docker build -t your-kiosk-image:latest .
    - docker tag your-kiosk-image:latest $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest

deploy_kiosk:
  stage: deploy
  script:
    - docker-compose down
    - docker-compose up -d
  only:
    - master

services:
  - docker:dind
