spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=true&requireSSL=true&verifyServerCertificate=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      connection-timeout: 30000
      maximum-pool-size: 30
      idle-timeout: 10
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.hibernate.format_sql: true
      hibernate.hibernate.default_batch_fetch_size: 100
    generate-ddl: true
    show-sql: true
  main:
    allow-bean-definition-overriding: true

jwt:
  secret: DevCoopKioskAuthCertificateJsonWebTokenSecretKey

server:
  servlet:
    context-path: /kiosk
    encoding:
      charset: UTF-8
      enabled: true
      force: true

db:
  imageUrl: './'
