spring:
  datasource:
    url: jdbc:mysql://10.0.5.4:6006/AriPay?serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true
    password: Devcoop1Qw@
    username: devcoop
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      connection-timeout: 30000
      maximum-pool-size: 30
      idle-timeout: 10
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.hibernate.format_sql: true
      hibernate.hibernate.default_batch_fetch_size: 100
    generate-ddl: true
    show-sql: true
  main:
    allow-bean-definition-overriding: true

jwt:
  secret: DevCoopKioskAuthCertificateJsonWebTokenSecretKey

server:
  servlet:
    context-path: /kiosk
    encoding:
      charset: UTF-8
      enabled: true
      force: true
